---
- name: Create directories
  hosts: mealie
  gather_facts: false

  vars:
    directories:
      - path: '/home/owen/mealie/data'

  roles:
    - common_create_directories

- name: Restore and Set Up Backups
  hosts: mealie
  gather_facts: false

  vars:
    directories:
      - source_path: '/home/owen/mealie/data'
        target_path: 'data'

  roles:
    - backup_directory_restore
    - backup_directory_backup

- name: Setup Melie
  hosts: mealie
  gather_facts: false

  roles:
    - podman_setup
    - mealie_copy_services

- name: Add firewall ports
  hosts: mealie
  gather_facts: false

  vars:
    ports:
      - port: 9000

  roles:
    - fedora_firewall_enable_ports

- name: Add Podman secrets
  hosts: mealie
  gather_facts: false

  vars:
    secrets:
      - key: OIDC_CLIENT_SECRET
        value: "{{ authentik_oidc_mealie_client_secret }}"

  roles:
    - podman_secrets_add

- name: Install container
  hosts: mealie
  gather_facts: false

  vars:
    service_name: mealie

  roles:
    - podman_containers_start
