# Configures the container, adding a non-root user to use for SSH.
- name: Configure Immich
  hosts: immich
  gather_facts: true
  become: true

  vars_files:
    - secrets.yaml

  roles:
    - configure_container

- name: Setup Docker
  hosts: immich
  gather_facts: true
  become: true

  vars_files:
    - secrets.yaml

  roles:
    - docker_setup
