---
# Following steps provided here: https://caddyserver.com/docs/install#static-binaries

- name: Install Dependent Packages
  ansible.builtin.apt:
    name:
    - debian-keyring
    - debian-archive-keyring
    - apt-transport-https
    - curl
  become: yes

- name: Ensure Dependency is Absent (caddy-stable-archive-keyrings.gpg)
  ansible.builtin.file:
    path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    state: absent
  become: yes
    
- name: Ensure Dependency is Absent (caddy-stable.list)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/caddy-stable.list
    state: absent
  become: yes

- name: Download Dependencies (caddy-stable-archive-keyrings.gpg)
  ansible.builtin.shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Download Dependencies (caddy-stable.list)
  ansible.builtin.shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

- name: Configure Permissions (caddy-stable-archive-keyrings.gpg)
  ansible.builtin.file:
    path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    mode: '004'
  become: yes

- name: Configure Permissions (caddy-stable.list)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/caddy-stable.list
    mode: '004'
  become: yes

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
  become: yes

- name: Create Caddy config directory
  ansible.builtin.file:
    path: /etc/caddy
    state: directory
    owner: caddy
    group: caddy
    mode: '0755'
  become: yes

- name: Template Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: '0644'
  become: yes
  notify: Reload Caddy

- name: Reload systemd
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
    daemon_reload: true
  become: yes
