# If the container isn't running, this will throw an error, which will be ignored.
# Is this the best way to do this? Almost certainly not.
# Does it work? You bet.
- name: Stop {{ service_name }}
  ansible.builtin.systemd_service:
    name: '{{ service_name }}'
    scope: "{{ 'system' if is_root_container | default(false) else 'user' }}"
    state: stopped
  become: "{{ is_root_container | default(false) }}"
  ignore_errors: true

#- name: Restart user daemon
#  ansible.builtin.systemd_service:
#    daemon_reload: true
#    scope: user

- name: Start {{ service_name }}
  ansible.builtin.systemd_service:
    name: '{{ service_name }}'
    state: started
    enabled: true
    daemon_reload: true
    scope: "{{ 'system' if is_root_container | default(false) else 'user' }}"
  become: "{{ is_root_container | default(false) }}"
