---
- name: Read Bouncer Config
  ansible.builtin.shell: cat /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
  register: bouncer_content
  become: true

- name: Set CrowdSec API Key
  set_fact:
    crowdsec_api_key: "{{ (bouncer_content.stdout | from_yaml).api_key }}"

- name: Template Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: "0644"
  become: true

- name: Template systemd service
  ansible.builtin.template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    mode: "0644"
  become: true

- name: Enable and reload Caddy service
  ansible.builtin.systemd:
    name: caddy
    enabled: yes
    state: reloaded
  become: true
