---
# Need to create VM for Nextcloud

# Configures the container, adding a non-root user to use for SSH.
- name: Configure Nextcloud
  hosts: nextcloud
  remote_user: root # root needs to be used initially to set up ansible user.
  gather_facts: true
  become: true
  become_user: root

  vars_files:
    - secrets.yaml

  vars:
    config_user: owen
    ansible_ssh_user: root

  roles:
    - configure_container

# Installs Nextcloud and sets up configurations
- name: Setup Nextcloud
  hosts: nextcloud
  gather_facts: false

  vars_files:
    - secrets.yaml

  roles:
    - nextcloud_setup

