---
- name: Restore and Set Up Backup (data)
  hosts: actual-budget
  gather_facts: false

  vars:
    backup_source_directory: '/home/owen/data'
    backup_target_directory: data

  roles:
    - backup_directory_restore
    - backup_directory_backup

- name: Setup Actual Budget
  hosts: actual-budget
  gather_facts: false

  roles:
    - podman_setup
    - actual_budget_setup

