---
- name: Restart user daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user

- name: Start service
  ansible.builtin.systemd_service:
    name: '{{ service_name }}'
    state: started
    enabled: true
    scope: user
