all:
  hosts:
    actual-budget:
      ansible_host: 192.168.100.164
      ansible_user: owen
      app_name: actual_budget
      container_number: 123
      podman_auto_update: true
    authentik:
      ansible_host: 192.168.100.157
      ansible_user: owen
      app_name: authentik
      container_number: 116
      database_name: authentik
    bento-pdf:
      ansible_host: 192.168.100.166
      ansible_user: owen
      app_name: bento_pdf
      container_number: 125
      podman_auto_update: true
    borg:
      ansible_host: 192.168.100.168
      ansible_user: owen
      app_name: borg
      container_number: 127
      podman_auto_update: true
    caddy:
      ansible_host: 192.168.100.151
      ansible_user: owen
      app_name: caddy
      container_number: 110
      # Get version from https://go.dev/dl/
      go_version: "1.25.5"
    home-assistant:
      ansible_host: 192.168.100.152
      ansible_user: owen
      app_name: home_assistant
      container_number: 111
    immich:
      ansible_host: 192.168.100.155
      ansible_user: owen
      app_name: immich
      container_number: 114
      immich_version: release
    it-tools:
      ansible_host: 192.168.100.163
      ansible_user: owen
      app_name: it_tools
      container_number: 122
      podman_auto_update: true
    linkwarden:
      ansible_host: 192.168.100.167
      ansible_user: owen
      app_name: linkwarden
      container_number: 126
      podman_auto_update: true
    navidrome:
      ansible_host: 192.168.100.156
      ansible_user: owen
      app_name: navidrome
      container_number: 115
      navidrome_version: "0.61.2"
    nextcloud:
      ansible_host: 192.168.100.159
      ansible_user: owen
      app_name: nextcloud
      container_number: 118
    obsidian:
      ansible_host: 192.168.100.165
      ansible_user: owen
      app_name: obsidian
      container_number: 124
      podman_auto_update: true
