all:
  hosts:
    proxmox:
      ansible_host: 192.168.200.155
      ansible_user: root
    caddy:
      ansible_host: 192.168.100.151
      ansible_user: owen
      ansible_python_interpreter: /usr/bin/python3
    jellyfin:
      ansible_host: 192.168.200.169
      ansible_user: owen
    navidrome:
      ansible_host: 192.168.100.156
      ansible_user: owen
    nextcloud:
      ansible_host: 192.168.100.159
      ansible_user: owen
    immich:
      ansible_host: 192.168.100.155
      ansible_user: owen
    plex:
      ansible_host: 192.168.200.154
      ansible_user: owen
