---
#- name: Install redis container
#  ansible.builtin.include_role:
#    name: podman_containers_start
#  vars:
#    service_name: nextcloud-redis

#- name: Setup database dump volume
#  ansible.builtin.systemd_service:
#    name: nextcloud-database-dump-volume
#    state: started
#    enabled: true
#    scope: user

#- name: Install database container
#  ansible.builtin.include_role:
#    name: podman_containers_start
#  vars:
#    service_name: nextcloud-database

#- name: Pause for 30 seconds for the database to start up
#  ansible.builtin.pause:
#    seconds: 30
#  when: initial_install | bool == true

#- name: Restore Database
#  ansible.builtin.include_role:
#    name: backup_postgresql_restore
#  vars:
#    service_name: nextcloud-database
#    postgres_user: nextcloud
#    database_name: nextcloud_database
#  when: initial_install | bool == true

#- name: Set Up Backup Database
#  ansible.builtin.include_role:
#    name: backup_postgresql_backup
#  vars:
#    service_name: nextcloud-database
#    postgres_user: nextcloud
#    database_name: nextcloud_database
#  when: initial_install | bool == true

#- name: Install nextcloud main container
#  ansible.builtin.include_role:
#    name: podman_containers_start
#  vars:
#    service_name: nextcloud

#- name: Install apache container
#  ansible.builtin.include_role:
#    name: podman_containers_start
#  vars:
#    service_name: nextcloud-apache

#- name: Install notify-push container
#  ansible.builtin.include_role:
#    name: podman_containers_start
#  vars:
#    service_name: nextcloud-notify-push

- name: Mount NAS NFS Share
  ansible.posix.mount:
    src: '{{ nas_ip }}:/mnt/Eve2/NAS'
    path: /mnt/truenas/nas
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
  become: true
  when: initial_install | bool == true

- name: Install nextcloud container
  ansible.builtin.include_role:
    name: podman_containers_start
  vars:
    service_name: nextcloud

- name: Pause for 30 seconds for the database to start up
  ansible.builtin.pause:
    seconds: 30
  when: initial_install | bool == true

- name: Restore Database
  ansible.builtin.include_role:
    name: backup_postgresql_restore
  vars:
    service_name: nextcloud-aio-mastercontainer-database
    postgres_user: nextcloud
    database_name: nextcloud_database
  when: initial_install | bool == true
